- docs/guide/pages/examples/dashboard.html
- docs/guide/templates/partials/examples-nav.hbs
- less/availity-app-icons-component.html
- less/availity-app-icons.less
- less/availity-mega-menu-component.html
- less/availity-navbar-component.html
- less/availity-variables.less
Adding app-icon-xs and -sm classes and updating default and -lg
> Adding app icon size classes

- docs/guide/pages/examples/dashboard.html
- docs/guide/templates/partials/examples-nav.hbs
- less/availity-app-icons-component.html
- less/availity-app-icons.less
- less/availity-mega-menu-component.html
- less/availity-navbar-component.html
- less/availity-variables.less
Removed a size and moved the classes up a level to make the default smaller
> Updated app icon class sizes to md (default), lg, and xl

- less/availity-type-component.html
- less/availity-type.less
adding text-truncate class for truncating text.
> adding class to truncate overflowing text

- less/availity-type-component.html
- less/availity-type.less
The class useful when dealing with text that wouldn't normally break in the responsive system e.g. filenames
> add text-break transformation class

- less/availity-app-icons-component.html
- less/availity-app-icons.less
- less/availity-panel.less
- less/availity-variables.less
closes #21 
Changed branded app icon classes and added others to match unbranded colors
> adding other branded app icon colors

- less/availity-list-group-component.html
- less/availity-list-group.less
This class is necessary when using anchor tags is not a viable option for list-group-items. Nested anchors are not valid html
> adding list-group-selectable

- less/availity-select2.less
* with icon font integration
* closes #36
> add style for select2 clear button

- docs/guide/pages/examples/notifications.html
- less/availity-buttons.less
- less/availity-dropdowns.less
- less/availity-mega-menu-component.html
- less/availity-mega-menu.less
- less/availity-variables.less
> GitHub issue 47 mega menu

- less/availity-labels-component.html
- less/availity-labels.less
- less/availity-type.less
- package.json
> block labels

- dist/css/availity-uikit.css
- docs/guide/pages/examples/authorization.html
- docs/guide/pages/examples/inbox.html
- less/availity-app-icons-component.html
- less/availity-aside.less
- less/availity-labels-component.html
- less/availity-labels.less
- less/availity-layouts.less
- less/availity-list-group.less
- less/availity-loading.less
- less/availity-panel.less
- less/availity-variables.less
Making sure all the colors are unified and match certain variable criteria. Must fit the new documentation of colors on https://confluence.availity.com/display/UTB/UI+Kit+Colors
> Updating and Unifying UiKit Colors

- less/availity-labels-component.html
- less/availity-labels.less
Adding some new colors to the regular labels.
> Additional Label Colors

- less/availity-variables-component.html
- less/pages/docs.less
Updating color components to match our system of color schemes. (I.E. Status colors now reflect status alerts, brand color was added, etc.)
> Updating color components

- less/availity-tables.less
> readding table header fix

- less/availity-buttons-component.html
updated examples relating to PR #78
> updating file upload examples

- less/availity-list-group-component.html
- less/availity-list-group.less
> Add primary list group item style and examples

- less/availity-badges-component.html
- less/availity-badges.less
- less/mixins/availity-mixins-badges.less
> adding badge variants

- bower.json
- less/availity-awesome-bootstrap-checkbox.less
- less/availity-bootstrap.less
- less/availity-external-libs.less
- less/availity-form-component.html
> adding awesome bootstrap checkboxes and radios

- docs/guide/pages/examples/authorization.html
- docs/guide/pages/examples/payer-spaces-page.html
- less/availity-type-component.html
- less/availity-type.less
* styles for branding apps with 3rd party logos
> branded apps

- docs/guide/templates/partials/examples-nav.hbs
> fixed the example-nav.hbs Logo and Home link, now routes to uikit index

- dev/docs.js
- dev/start.js
webpack.config.babel => webpack.config
> Fix #138; Rename webpackConfig

- less/availity-awesome-bootstrap-checkbox.less
> Fixed styles for labels on radio and checkboxes

- docs/content/components/wizard.html
Lemme know if you want the location and/or language for the disclaimer modified.
> Issue #146: Disabled Wizard Steps still respond to clicks.

- docs/content/components/buttons.html
Use <code>...</code> instead of inline markdown
> Fix formatting in buttons docs.

- docs/content/components/list-group.html
- scss/_list-group.scss
Change .list-group-cards to not default to secondary style, allowing for a non-styled card style
> non-styled list group cards item

- scss/_forms.scss
Closes #162
Address issue for date inputs within an input group in chrome.
> fix(forms): fix height/stacking issue for dates

- docs/content/components/wizard.html
- less/wizard.less
Changing progress to completed
Progress now adds a bar between elements
> Adding progress bar to wizard

- less/app-icons.less
- less/loading.less
- less/variables.less
Update Green App-icon gradient direction, increase loading indicator size
> Changes for #167

- packages/docs/src/bootstrap-components/mega-menu.md
- packages/docs/src/bootstrap-components/navbar-notifications.md
- packages/docs/src/bootstrap-components/navbar-secondary.md
- packages/docs/src/components/Navigation.js
https://github.com/Availity/availity-uikit/issues/186
> add aria-label to navbar buttons

- packages/docs/src/bootstrap-components/badges-removeable.md
- packages/docs/src/bootstrap-components/buttons-file-upload.md
- packages/docs/src/bootstrap-components/forms-validation.md
- packages/docs/src/bootstrap-components/forms.md
- packages/docs/src/bootstrap-components/mega-menu.md
- packages/docs/src/bootstrap-components/navbar-forms.md
- packages/docs/src/bootstrap-components/navbar-notifications.md
- packages/docs/src/bootstrap-components/navbar-secondary.md
- packages/docs/src/bootstrap-components/typography-header-logo.md
https://github.com/Availity/availity-uikit/issues/190
> links and form element labels, typo fix

- packages/uikit/scss/_variables.scss
https://github.com/Availity/availity-uikit/issues/194
> cards text-muted color update

- packages/uikit/scss/_variables.scss
- packages/uikit/scss/mixins/_type.scss
lowest contrast color should be compliant
> headers and icon color updates

- packages/uikit/scss/_buttons.scss
- packages/uikit/scss/_variables.scss
https://github.com/Availity/availity-uikit/issues/193
https://github.com/Availity/availity-uikit/issues/196 (warning text)
> buttons color update

- packages/uikit/scss/_forms.scss
https://github.com/Availity/availity-uikit/issues/199
> Feature/v3 select color contrast/background

- packages/docs/package.json
- packages/docs/src/bootstrap-components/forms-checkboxes.md
- packages/docs/src/bootstrap-components/forms-inline.md
- packages/docs/src/bootstrap-components/forms-radios.md
- packages/docs/src/components/Browser.js
- packages/docs/src/components/Browser.scss
- packages/docs/src/components/Footer.js
- packages/docs/src/components/Footer.scss
- packages/docs/src/components/Navigation.js
- packages/docs/src/components/Navigation.scss
- packages/docs/src/layouts/index.js
- packages/docs/src/layouts/index.scss
- packages/docs/src/pages/index.js
- packages/uikit/package.json
- packages/uikit/scss/_forms.scss
https://github.com/Availity/availity-uikit/issues/215
More to come..
> chore(availity-uikit): update to bs4 + update landing page

- packages/uikit/scss/_variables.scss
> feat(availity-uikit): add bg-faded styles

- package-lock.json
- packages/docs/src/bootstrap-components/wizard-bar.md
- packages/docs/src/bootstrap-components/wizard-icons.md
- packages/docs/src/bootstrap-components/wizard-progress.md
- packages/docs/src/bootstrap-components/wizard.md
- packages/uikit/package-lock.json
- packages/uikit/scss/_wizard.scss
Created new progress stepwizard and a minor update to how the hover effects work. 
Progress now adds progress bars between each step, with completed steps getting a green bar after and gray everywhere else.
The default step style no longer has the hover effect, but is added by using an <a> or `stepwizard-step-clickable` to that step.
the old stepwizard-progress is now called stepwizard-icons
If names need to be adjusted for better ones or to avoid potential breaking changes I am open to that
(Side note: the stacked progress step wizard has some bad behavior if text wraps, not sure if this can be solved without needing a different table structure for stacked progress)
> New wizard-bar and docs

- packages/uikit/scss/_variables.scss
This makes the card-header and border darker for better visibility
> fix(uikit): darken card header and border

- .github/workflows/deploy.yml
- .github/workflows/pr-build.yml
- .prettierignore
- CHANGELOG.md
- package.json
- packages/uikit/package.json
- packages/uikit/scss/_type.scss
- scripts/release.sh
Fixed import and testing things with github actions
> chore: release v4.6.1 [skip ci]
